name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: |
          docker build --rm -f "miniconda3/debian/Dockerfile" -t xdev-miniconda:latest "miniconda3/debian" --build-arg PYTHON_VERSION=3.6
